### ISSUE TITLE
Add Desktop OTA-DFU Option To Readme.md

### ISSUE THREAD

**Issue by fwg-cag** [daniel-thompson/wasp-os#11]
Hi!

Some people may prefer a desktop solution for OTA DFUing micropython.zip. I found that https://github.com/dingari/ota-dfu-python works well for this:
`sudo $HOME/ota-dfu-python/dfu.py -z $HOME/wasp-os/micropython.zip -a D6:62:01:XX:XX:XX --legacy`
You may want to update your docu accordingly.

BR, piner4711

PS: Great work BTW!

**Comment by purlupar** [comment]
Great! In the pinetime chat, Peetz0r said that one needs to say " --legacy" for the UUID to work correctly.


-------- Ursprüngliche Nachricht --------
Von: fwg-cag <notifications@github.com>
Gesendet: 11. April 2020 10:35:31 MESZ
An: daniel-thompson/wasp-os <wasp-os@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Betreff: [daniel-thompson/wasp-os] Add Desktop OTA-DFU Option To Readme.md (#11)

Hi!

Some people may prefer a desktop solution for OTA DFUing micropython.zip. I found that https://github.com/dingari/ota-dfu-python works well for this:
`sudo $HOME/ota-dfu-python/dfu.py -z $HOME/wasp-os/micropython.zip -a D6:62:01:XX:XX:XX`
You may want to update your docu accordingly.

BR, piner4711

PS: Great work BTW!

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/daniel-thompson/wasp-os/issues/11

**Comment by daniel-thompson** [comment]
> Some people may prefer a desktop solution for OTA DFUing micropython.zip.

Some people definitely includes me... I just haven't found anything suitable quite yet!

On the other hand, given wasp-os is a Python-based project, I'm very reluctant to recommend tools that are still based around python 2 (which is no longer supported upstream). I've done a mechanical port to python3 using 2to3 and fixed up a few obvious string versus bytes issues but it is not quite enough to get the tool running in Python 3.

I will try to take another look when I finished the current round of frenzied hacking on wasp-os itself.

**Comment by daniel-thompson** [comment]
Just a quick follow up. I've managed to hack together something that runs in python3 but there's still a bit of debugging needed (in particular if you walk away from the laptop when wearing the watch then the error recovery code hits some bytes vs string issues I haven't tidied up yet).

**Comment by daniel-thompson** [comment]
Fixed in the most recent round of updates..
