### ISSUE TITLE
Add Line drawing function to draw565 library

### ISSUE THREAD

**Issue by Kozova1** [daniel-thompson/wasp-os#118]
I noticed that the drawing library apparently does not support lines.
Is it possible to add a line drawing function?

I tried hacking in a line function but couldn't figure out how to write directly to the screen.

**Comment by Kozova1** [comment]
Ideally, it would have an API like this:

`watch.drawable.line(x1,y1,x2,y2, color)`

maybe even add a thickness option?

**Comment by daniel-thompson** [comment]
No objections here. One of the Bressenham variations should work fine.

**Comment by Kozova1** [comment]
If you can help me understand how raw writing to the display works (quick_write etc.) I'll get a PR for it.

**Comment by daniel-thompson** [comment]
quick_write() (which is designed to stop you having to keep pointlessly toggling the chip select) won't do you any good here because you can only write a couple of bytes at a time. You'll need to use display.set_window() to select the "rectangle" you want to update (start of with a 1x1 rectangle) and then use display.write() to draw the pixel.

Note drawing angled lines directly into the video RAM will be very slow because there's pretty much no way to optimise the transfer of data.
It will be very slow...

**Comment by Kozova1** [comment]
see pr #124
