### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by SecureCodeJIT** [daniel-thompson/wasp-os#126]
Improvement

- link to cell phone for text and email notifications

**Comment by Izaic** [comment]
I'd imagine this is on the gadgetbridge side of things, not WaspOS itself. That said i agree!

**Comment by Kozova1** [comment]
A custom gadgetbridge build exists that supports it - https://github.com/daniel-thompson/gadgetbridge

**Comment by SecureCodeJIT** [comment]
i use nRFconnect gadgetbridge is not working for me yet.

**Comment by Kozova1** [comment]
Official gadgetbridge doesn't work - you have to build the one I linked above from source

**Comment by daniel-thompson** [comment]
Agree. The custom Gadgetbridge has been available to use since July!

I have recently set up an autobuilder so you don't have to compile it yourself. Generally speaking you can go to the most recent build and then grab the arteacts from the bottom of the page. See:
https://github.com/daniel-thompson/gadgetbridge/actions?query=event%3Apush+

**Comment by pathcl** [comment]
@daniel-thompson what if you’re on iOS? or you want to send data using your own linux box? is it possible?. Use case: send notifications for gmail, prometheus, twitter, so on.
