### ISSUE TITLE
Filesystem in simulator

### ISSUE THREAD

**Issue by Kozova1** [daniel-thompson/wasp-os#135]
This might be a dumb question, but is it possible to simulate files with the simulator? If yes, how?

**Comment by daniel-thompson** [comment]
The simulator is simply a regular (not-micro)python interpretter with some addition SDL glue code to emulate the display and touch screen. That means the filesystem will work exactly like it does in regular python (e.g. open('fname.txt') will open fname.txt in the current directory). Providing you avoid absolute paths (which you should anyway because different micropython implementations mount the fs in different places) then the simulator and the device should work pretty much the same.
