### ISSUE TITLE
Digits on Chrono watchface

### ISSUE THREAD

**Issue by Jab2870** [daniel-thompson/wasp-os#158]
Hi,

Thanks for creating this amazing system.

This isn't really an issue but there isn't really anywhere else to put this.

I have made a slight adjustment to the Chrono watch face so that it shows
numbers rather than lines at the hour markers. This is obviously a pretty small
change, and I'd be happy to create a PR as it is, but I thought it might be nice
if the user is able to make the choice somehow.

One option would be to have 2 apps, however I think this is not ideal.

Option 2 would be to have a variable in the ChronoApp that determines whether to
show numbers or lines. This would be better than option 1.

My preferred option would be to have a setting somewhere. Being pretty new to
the wasp-os project, I wanted to check if there is a way for apps to register
settings in the settings app?

Thanks again and I look forward to hearing your feedback.
![2021-01-23T11-15-44Z](https://user-images.githubusercontent.com/1909202/105576687-6f4b7780-5d6c-11eb-82db-cb74d9a94a61.png)

**Comment by daniel-thompson** [comment]
Sorry for the delay.

To be honest I'd rather see the user preference handled by letting them choose between differen watch face apps (there's no point in presenting the user with a preference in the settings app for a watch face they are not using).

That means you can send a PR for your watch face as a seperate apps although please make appropriate changes to ChonoApp so that the two applications can share as much code as possible. Maybe even implement the second app in the same file).

Currently there are only three but once we collect enough watch faces, we can move them out of the Software app into a watch face selector tool.
