### ISSUE TITLE
[bootloader] OTA for reverting to nRF bootloader

### ISSUE THREAD

**Issue by ildar** [daniel-thompson/wasp-os#177]
as OTA zip.
Also is it requited to use "reloader" for that?

**Comment by daniel-thompson** [comment]
Take a look at the Warning text at the bottom of https://wasp-os.readthedocs.io/en/latest/install.html#daflasher-for-android .

Also be very careful... it is easy to brick things since the Deesay DS-D6 bootloader isn't really intended to run on P8 (there are no graphical indicators that it is running but you will be able to see it in DaFlasher).

**Comment by ildar** [comment]
Thank you for pointing to that part. I don't know how I missed that.
Yes, it worked from DaFlasher (though failed from dfu.py)
/close
