### ISSUE TITLE
calculator: using the multiplication operator twice results in a pow calculation. 

### ISSUE THREAD

**Issue by Liorst4** [daniel-thompson/wasp-os#208]
There is an effort to abstract the python syntax of the calculations (replacing `^` with `**`), but still, if you input `*` twice, it evaluates into a `pow` operation instead of a "syntax error". This might be confusing for users that are not familiar with python.

**Comment by daniel-thompson** [comment]
I think I'm inclined to view this as an easter egg rather than a bug since even a user unfamiliar with python should know that 4 ** 2 may not evaluate as intended.

Moreover explicitly forbidding ** to protect uses unfamiliar with python expressions would also imply banning the use of // and that case (integer division) is a potentially useful easter egg for some users.
