### ISSUE TITLE
Porting wasp-os to nRF52840-based devices

### ISSUE THREAD

**Issue by pratyush049** [daniel-thompson/wasp-os#71]
Hello sir,

i want to upgrade wasp os to nrf54840 controller. what process should i follow to do changes? how to do configuration?  i feel so interesting to work on wasp os, just want to upgrade IC so that i can use more number of sensors.

Thanks in advance.

**Comment by daniel-thompson** [comment]
The answer is pretty much the same as https://github.com/daniel-thompson/wasp-os/issues/27#issuecomment-634717107 to be honest. You need to port micropython, bootloader and wasp-os itself. There are already examples of nRF52840 boards in both micropython and bootloader. wasp-os itself doesn't really care about the chip so that will just be a normal board port.

You will get build problems with the reloader but whilst startinng out you can just disable the build.
