### ISSUE TITLE
Shared base class for apps

### ISSUE THREAD

**Issue by cr0mbly** [daniel-thompson/wasp-os#96]
### Summary

One of the things that seems like a good change going forward for future developers coming into this project is implementing a `BaseApp` class with expected hooks that the Wasp-os is expecting to be defined. We kinda have this with the TestApp which lays out which functions you can hook into in order to interact with hardware and the rest of the OS. I was thinking something like this:

```Python

class BaseApp:
    """Base class that all apps inherit from. Defines hooks into 
    the application that can be tied into."""
    NAME = None
    ICON = None

    def __init__(self):
        if self.NAME is None:
            raise NotImplemented('Application requires a name')
        if self.ICON is None:
            raise NotImplemented('Application requires an icon')

    def foreground(self):
        """process run on application startup"""
        pass

    def background(self):
        """Background process run on close"""
        pass

    def press(self, button, state):
        """Registered caller for touch events"""
        pass

    def swipe(self, event):
        """Registered caller for swipe events"""
        pass

    def sleep(self):
        """
        Registered hook for if an app should go into sleep mode. 
        Default is True, override to change.
        """
        return True
    
    def tick(self):
        """Registered hook for application runtime process"""
        pass

    def touch(self, event):
        """Registered caller for touch event"""
        pass

    def draw(self):
        """Registered caller rendering application display"""
        pass
```

This is especially handy when coding through VIM/IDEs where they can take advantage of these signatures to help guide the developer

**Comment by daniel-thompson** [comment]
Not having a base class was a deliberate choice. Python is a dynamic language and uses can use duck-typing for polymorphism. As such it just feel right to me to have a base class full of pass functions.

However, what wasp-os does have is a TemplateApp that is pretty much identical to your base class. I expected people to copy the template app, filling in the implementation and deleting whatever calls are inappropriate. However an IDE user who wants signature tooltips rather than a template could inherit from the TemplateApp if they want to.
